#!/usr/bin/env python3
"""Regenerates src/24_report_brand_assets.js from the files in brand/.

The partner report embeds the Trail Blazers design system's fonts and logos so
it renders identically offline. They live here as files; this script packs them
into a JS constant the build concatenates like any other src/ file.

Run after changing anything in brand/fonts or brand/logos:  python3 brand/make_assets.py
"""
import base64
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / 'src' / '24_report_brand_assets.js'

FONTS = {
    'leagueGothic': 'fonts/LeagueGothic-Regular.woff2',
    'tradeGothic': 'fonts/TradeGothic-Cn18.woff2',
    'tradeGothicBold': 'fonts/TradeGothic-BdCn20.woff2',
}
LOGOS = {
    'stacked': 'logos/blazers-global-stacked.png',
    'wordmark': 'logos/portland-wordmark-horiz.png',
}


def data_uri(rel: str, mime: str) -> str:
    return f'data:{mime};base64,' + base64.b64encode((HERE / rel).read_bytes()).decode('ascii')


def main() -> None:
    assets = {
        'fonts': {k: data_uri(v, 'font/woff2') for k, v in FONTS.items()},
        'logos': {k: data_uri(v, 'image/png') for k, v in LOGOS.items()},
    }
    OUT.write_text(
        '// GENERATED by brand/make_assets.py from brand/ — do not edit by hand.\n'
        '// Trail Blazers design system fonts and logos for the partner report.\n'
        '// Logo art (c) NBA Properties, Inc.\n'
        f'const REPORT_BRAND_ASSETS = {json.dumps(assets, indent=1)};\n',
        encoding='utf-8',
    )
    print(f'Wrote {OUT} ({OUT.stat().st_size // 1024} KB)')


if __name__ == '__main__':
    main()
